# Generated by Django 4.1.2 on 2022-10-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=75)),
                ('region', models.CharField(max_length=75)),
                ('latitude', models.CharField(max_length=75)),
                ('longitude', models.CharField(max_length=75)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=99)),
                ('description', models.TextField(blank=True, null=True)),
                ('project_url', models.URLField()),
                ('src_url', models.URLField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=99, null=True)),
                ('image', models.ImageField(upload_to='img/')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('project', models.ManyToManyField(related_name='image', to='dashboard.myproject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
