# Generated by Django 4.1.2 on 2022-10-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectimage",
            name="alt_text",
        ),
        migrations.RemoveField(
            model_name="projectimage",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="projectimage",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="myproject",
            name="project_url",
            field=models.URLField(help_text="Required"),
        ),
    ]
