# Generated by Django 4.1.2 on 2022-10-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.AddField(
            model_name='myproject',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, related_name='images', to='dashboard.projectimage'),
        ),
    ]
