# Generated by Django 4.1.2 on 2022-10-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_projectimage_project_myproject_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
            ],
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='myproject',
            name='tool',
            field=models.ManyToManyField(blank=True, null=True, related_name='tools', to='dashboard.projecttool'),
        ),
    ]
