# Generated by Django 4.1.2 on 2022-10-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_remove_projectimage_alt_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectimage",
            name="is_feature",
        ),
        migrations.AddField(
            model_name="projectimage",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
