# Generated by Django 4.1.2 on 2022-10-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_aboutprojects_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutProjects',
            new_name='AboutProject',
        ),
    ]
