# Generated by Django 4.1.2 on 2022-10-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_aboutprojects_aboutproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutproject',
            name='article',
            field=models.TextField(blank=True, null=True),
        ),
    ]
