# Generated by Django 4.1.2 on 2022-10-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_projecttool_alter_projectimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='name',
        ),
        migrations.AlterField(
            model_name='myproject',
            name='image',
            field=models.ManyToManyField(related_name='images', to='dashboard.projectimage'),
        ),
        migrations.AlterField(
            model_name='myproject',
            name='tool',
            field=models.ManyToManyField(related_name='tools', to='dashboard.projecttool'),
        ),
    ]
