# Generated by Django 4.1.2 on 2022-10-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_aboutproject_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutproject',
            old_name='article',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='aboutproject',
            old_name='name',
            new_name='project_title',
        ),
        migrations.RenameField(
            model_name='aboutproject',
            old_name='code_url',
            new_name='project_url',
        ),
        migrations.RenameField(
            model_name='aboutproject',
            old_name='another_url',
            new_name='src_url',
        ),
        migrations.RemoveField(
            model_name='aboutproject',
            name='image',
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='images',
            field=models.FileField(blank=True, default='https://images.unsplash.com/photo-1515879218367-8466d910aaa4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80', null=True, upload_to='img/'),
        ),
    ]
